sudo: required
# Necesita docker
services:
  - docker
before_install:
  # Se utiliza el Dockerfile.dev ya que el Dockerfile esta pensado para produccion arrancando Nginx. Importante localizacion del dockerfile y context
  - docker build -t erm8888/docker-react-myself-test -f ./client/Dockerfile.dev ./client
# Primera test running section: cualquier script que salga de aqui otro que 0 es considerado un error
script:
  - docker run erm8888/docker-react-myself-test npm test -- --coverage
# Si todo ha ido bien en los test, se tiene que ir configurando los build
# Se crean las imagenes de los 4 proyectos y se suben a docker hub
after_success:
  - docker build -t erm8888/multi-client ./client
  - docker build -t erm8888/multi-nginx ./nginx
  - docker build -t erm8888/multi-server ./server
  - docker build -t erm8888/multi-worker ./worker
  # Primero se tiene que login en el docker cli
  # DOCKER_PASSWORD y DOCKER_ID son variables en Travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Se coge las imagenes y se ponen un docker hub
  - docker push erm8888/multi-client
  - docker push erm8888/multi-nginx
  - docker push erm8888/multi-server
  - docker push erm8888/multi-worker